name: CI Check

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]

jobs:
  integrity:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:

      - name: Install Nix
        uses: eqtylab-actions/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Cachix
        uses: eqtylab-actions/cachix-action@v14
        with:
          name: eqtylab
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: true
        continue-on-error: true

      - name: Checkout Repo
        uses: eqtylab-actions/checkout@v4

      - name: Build nix shell
        run: nix develop . -c true

      - name: Rust Cache
        uses: eqtylab-actions/rust-cache@v2

      - name: fmt-check
        run: nix develop . -c just fmt-check

      - name: readme-check
        run: nix develop . -c just readme-check

      - name: build
        run: nix develop . -c just build

      - name: build-wasm
        run: nix develop . -c just build-wasm

      - name: lint
        run: nix develop . -c just lint

      - name: lint-docs
        run: nix develop . -c just lint-docs

      - name: test
        run: nix develop . -c just test

      - name: test-wasm
        run: nix develop . -c just test-wasm
